### ISSUE TITLE
sprint 1 reflection

### ISSUE THREAD

**Issue by tj-scherer** [MatthewEGasper/emStart#57]

**Comment by tj-scherer** [comment]
- off to a good start
- working in the lab is important to get stuff done
- we did a good job streamlining the hardware ordering process
- we will need to improve documentation a lot

**Comment by MatthewSelph** [comment]
- Took a chunk of time clearing up what Dr.Liu wanted for this semester.
- Process for ordering parts went smoother than the previous semester.
